import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>DotSei-Metadata</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://dotsei.me">DotSei</a>
        </h1>

        <p className={styles.description}>
          Endpoints:
          <div className={styles.ul}>
            <div className={styles.uui}>
              <code lang="javascript" className={styles.code}>
                <code>
                  <p className={styles.uuiSub}>
                    To get information on domain name using token id.
                  </p>
                  <p className={styles.uuiSub}>
                    get
                    (https://dotsei-metadata-service.vercel.app/api/:tokenId)
                  </p>
                </code>
              </code>
            </div>
            <div className={styles.uui}>
              <code lang="javascript" className={styles.code}>
                <code>
                  <p className={styles.uuiSub}>
                    To get Image of the domain name.
                  </p>
                  <p className={styles.uuiSub}>
                    get
                    (https://dotsei-metadata-service.vercel.app/api/image/:domainName)
                  </p>
                </code>
              </code>
            </div>
          </div>
        </p>
        <div>
          <p className={styles.description}>Example:</p>
          <img src="/domainInfo.png" alt="" width={900} />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
